/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import DAO.ConsultaDAO;
import DAO.MultaDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.Consulta;
import negocio.Prestamo;

/**
 *
 * @author Paola Becerra
 */
public class DescargarPrestamoFrame extends javax.swing.JFrame {

    /**
     * Creates new form DescargarPrestamoFrame
     */
    public DescargarPrestamoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        num_prestamo = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        descargar = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        b_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel1.setText("Numero de Prestamo");

        num_prestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_prestamoActionPerformed(evt);
            }
        });

        buscar.setBackground(new java.awt.Color(153, 0, 0));
        buscar.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        buscar.setForeground(new java.awt.Color(255, 255, 255));
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        descargar.setBackground(new java.awt.Color(153, 0, 0));
        descargar.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        descargar.setForeground(new java.awt.Color(255, 255, 255));
        descargar.setText("Descargar ");
        descargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descargarActionPerformed(evt);
            }
        });

        atras.setBackground(new java.awt.Color(153, 0, 0));
        atras.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        atras.setForeground(new java.awt.Color(255, 255, 255));
        atras.setText("Atras");

        b_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo", "Estado", "ID Reserva", "Multa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(b_table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(num_prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buscar)
                        .addGap(49, 49, 49)
                        .addComponent(descargar)
                        .addGap(18, 18, 18)
                        .addComponent(atras))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num_prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descargar)
                    .addComponent(buscar)
                    .addComponent(atras))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num_prestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_prestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_prestamoActionPerformed

    private void descargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descargarActionPerformed
        int fila = b_table.getSelectedRow();
        Long cod = (Long) b_table.getValueAt(fila, 0);
        System.out.println("" + cod);
        ConsultaDAO c = new ConsultaDAO();
        MultaDAO m = new MultaDAO();
        //validar las multas 
        System.out.println("antes del int" + c.obtenerDiasPrestamo(cod));
        int dias = c.obtenerDiasPrestamo(cod);
        System.out.println("antes de registrar la multa");

        if (dias > 0) {
            m.registrarMulta(cod);
            System.out.println("despues de registrar la multa");
            String[] opciones = {"Pagar", "Atras"};
            int x = JOptionPane.showOptionDialog(null, "Sistema de Prestamos. El prestamo seleccionado tiene multa. ",
                    "Prestamos",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opciones, opciones[0]);
            System.out.println("" + x);
            if (x == 0) {
                System.out.println("antes de pagar multa");
                c.pagarMulta(cod);
                System.out.println("despues de pagar multa");
            } else if (x == 1) {
                
            }
                c.descargarPrestamo(cod);
        } else {
                c.descargarPrestamo(cod);

        } 
        
    }//GEN-LAST:event_descargarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        DefaultTableModel model = (DefaultTableModel) b_table.getModel();
        Long a = Long.valueOf(num_prestamo.getText());
        for (Prestamo con : ConsultaDAO.buscarPrestamo(a)) {
            model.addRow(new Object[]{con.getNum_prestamo(), con.getTi_prestamo(),
                con.getEst_prestamo(), con.getNum_reserva()});
        }


    }//GEN-LAST:event_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DescargarPrestamoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DescargarPrestamoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DescargarPrestamoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DescargarPrestamoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DescargarPrestamoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JTable b_table;
    private javax.swing.JButton buscar;
    private javax.swing.JButton descargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField num_prestamo;
    // End of variables declaration//GEN-END:variables
}
