/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import DAO.ConsultaDAO;
import DAO.PrestamoDAO;
import java.sql.Date;
import java.util.Calendar;
import java.util.Objects;
import javax.swing.JOptionPane;
import negocio.Prestamo;

/**
 *
 * @author Paola Becerra
 */
public class ValidarPrestamoFrame extends javax.swing.JFrame {

    /**
     * Creates new form ValidarPrestamoFrame
     */
    public ValidarPrestamoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cod_estudiante = new javax.swing.JTextField();
        num_reserva = new javax.swing.JTextField();
        ti_prestamo = new javax.swing.JComboBox<>();
        pre_date = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Codigo Estudiante");

        jLabel2.setText("Numero de Reserva");

        jLabel3.setText("Tipo de Prestamo");

        jLabel4.setText("Fecha");

        ti_prestamo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prestamo", "Domicilio", "Sala" }));

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Atras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(56, 56, 56)
                        .addComponent(jButton3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(131, 131, 131)
                                .addComponent(pre_date, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(77, 77, 77)
                                .addComponent(ti_prestamo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(65, 65, 65)
                                .addComponent(num_reserva))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(cod_estudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cod_estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(num_reserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ti_prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(pre_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String bien = "Prestamo Registrado";
        //Guartar un prestamo
        // hallar el codigo de la copia reservada
        Prestamo prestamo = new Prestamo();
        PrestamoDAO prestamoDAO = new PrestamoDAO();
        ConsultaDAO consulta = new ConsultaDAO();
        //Llenar el prestamo
        Long id_reserva = Long.valueOf(num_reserva.getText());
        Long a = consulta.consultarIdMaterial(prestamo.getNum_reserva());
        // fecha
        String dd = Integer.toString(pre_date.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mm = Integer.toString(pre_date.getCalendar().get(Calendar.MONTH) + 1);
        String yyyy = Integer.toString(pre_date.getCalendar().get(Calendar.YEAR));
        String date = yyyy + "-" + mm + "-" + dd;
        Date f = java.sql.Date.valueOf(date);

        prestamo.setNum_reserva(id_reserva);
        prestamo.setFe_inicio(f);
        prestamo.setEst_prestamo("ACT");

        //fecha limite
        Calendar today = Calendar.getInstance(); //Creas valiable de tipo calendar
        Long prueba = consulta.consultarMaterialBibliografico(a);
        System.out.println("numero id"+a);
        System.out.println("prueba " +prueba);
        System.out.println("antes del if");

        if (Objects.equals(prueba, "null")){
            today = pre_date.getCalendar();
            today.add(Calendar.DAY_OF_MONTH, 2);
            String ddl=Integer.toString(today.get(Calendar.DAY_OF_MONTH));
            String mml = Integer.toString(today.get(Calendar.MONTH)+1);
            String yyyyl = Integer.toString(today.get(Calendar.YEAR));
            String date2 = yyyyl+"-"+mml+"-"+ddl;
            Date fl = java.sql.Date.valueOf(date2);
            prestamo.setFe_limite(fl);

        } else {
            System.out.println("entro en bibliografico");
            today = pre_date.getCalendar();
            today.add(Calendar.DAY_OF_MONTH, 4);
            String ddl=Integer.toString(today.get(Calendar.DAY_OF_MONTH));
            String mml = Integer.toString(today.get(Calendar.MONTH)+1);
            String yyyyl = Integer.toString(today.get(Calendar.YEAR));
            String date2 = yyyyl+"-"+mml+"-"+ddl;
            Date fl = java.sql.Date.valueOf(date2);
            prestamo.setFe_limite(fl);
        }

        // a es el id del material, con ello consultar el numero de copias existente de ese material
        String b = consulta.contarCopiasMaterial(a);

        System.out.println("" + a);
        int c = Integer.parseInt(b);
        // validar que no exista una multa pendiente

        // validar que tipo de prestamos fue solicitado
        String tipo = ti_prestamo.getSelectedItem().toString();

        if (tipo.equals("Domicilio")) {
            // verificar que existe mas de una copia
            if (c > 1) {
                prestamo.setTi_prestamo("D");
                String resp = PrestamoDAO.registrarPrestamo(prestamo);
            } else {
                JOptionPane.showMessageDialog(null, "El material seleccionado solo puede ser consultado en sala");
            }
        } else if (tipo.equals("Sala")){
            prestamo.setTi_prestamo("S");
            String resp = PrestamoDAO.registrarPrestamo(prestamo);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String bien = "Prestamo Registrado";
        //Guartar un prestamo
        // hallar el codigo de la copia reservada
        Prestamo prestamo = new Prestamo();
        PrestamoDAO prestamoDAO = new PrestamoDAO();
        ConsultaDAO consulta = new ConsultaDAO();
        //Llenar el prestamo
        Long id_reserva = Long.valueOf(num_reserva.getText());
        Long a = consulta.consultarIdMaterial(id_reserva);
        // fecha
        String dd = Integer.toString(pre_date.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mm = Integer.toString(pre_date.getCalendar().get(Calendar.MONTH) + 1);
        String yyyy = Integer.toString(pre_date.getCalendar().get(Calendar.YEAR));
        String date = yyyy + "-" + mm + "-" + dd;
        Date f = java.sql.Date.valueOf(date);

        prestamo.setNum_reserva(id_reserva);
        prestamo.setFe_inicio(f);
        prestamo.setEst_prestamo("ACT");

        //fecha limite
        Calendar today = Calendar.getInstance(); //Creas valiable de tipo calendar
        Long prueba = consulta.consultarMaterialBibliografico(a);
        String pruebaS = prueba+"";
        System.out.println("numero id"+a);
        System.out.println("prueba " +prueba);
        System.out.println("antes del if");

        if (pruebaS.equals("null")){
            today = pre_date.getCalendar();
            today.add(Calendar.DAY_OF_MONTH, 2);
            String ddl=Integer.toString(today.get(Calendar.DAY_OF_MONTH));
            String mml = Integer.toString(today.get(Calendar.MONTH)+1);
            String yyyyl = Integer.toString(today.get(Calendar.YEAR));
            String date2 = yyyyl+"-"+mml+"-"+ddl;
            Date fl = java.sql.Date.valueOf(date2);
            prestamo.setFe_limite(fl);

        } else {
            System.out.println("entro en bibliografico");
            today = pre_date.getCalendar();
            today.add(Calendar.DAY_OF_MONTH, 4);
            String ddl=Integer.toString(today.get(Calendar.DAY_OF_MONTH));
            String mml = Integer.toString(today.get(Calendar.MONTH)+1);
            String yyyyl = Integer.toString(today.get(Calendar.YEAR));
            String date2 = yyyyl+"-"+mml+"-"+ddl;
            Date fl = java.sql.Date.valueOf(date2);
            prestamo.setFe_limite(fl);
        }

        // a es el id del material, con ello consultar el numero de copias existente de ese material
        String b = consulta.contarCopiasMaterial(a);

        System.out.println("" + a);
        int c = Integer.parseInt(b);
        // validar que no exista una multa pendiente

        // validar que tipo de prestamos fue solicitado
        String tipo = ti_prestamo.getSelectedItem().toString();

        if (tipo.equals("Domicilio")) {
            // verificar que existe mas de una copia
            if (c > 1) {
                prestamo.setTi_prestamo("D");
                String resp = PrestamoDAO.registrarPrestamo(prestamo);
            } else {
                JOptionPane.showMessageDialog(null, "El material seleccionado solo puede ser consultado en sala");
            }
        } else if (tipo.equals("Sala")){
            prestamo.setTi_prestamo("S");
            String resp = PrestamoDAO.registrarPrestamo(prestamo);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValidarPrestamoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValidarPrestamoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValidarPrestamoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValidarPrestamoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValidarPrestamoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cod_estudiante;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField num_reserva;
    private com.toedter.calendar.JDateChooser pre_date;
    private javax.swing.JComboBox<String> ti_prestamo;
    // End of variables declaration//GEN-END:variables
}
